name: Push Branch

on:
  push:
    branches:
      - '*'

env: {}

jobs:
  get-date:
    name: Date
    uses: silnith/github-workflows/.github/workflows/bash-get-date.yaml@main

  maven-cache:
    name: Maven Cache
    permissions:
      contents: read
      packages: read
    needs:
      - get-date
    uses: silnith/github-workflows/.github/workflows/maven-cache-dependencies.yaml@main
    with:
      java-version: 17
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
  maven-verify:
    name: Maven
    permissions:
      contents: read
      packages: read
    needs:
      - get-date
      - maven-cache
    uses: silnith/github-workflows/.github/workflows/maven-verify.yaml@main
    with:
      java-version: 17
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
  maven-test-results:
    name: Maven Test Results
    permissions:
      checks: write
    needs:
      - maven-verify
    uses: silnith/github-workflows/.github/workflows/publish-test-results.yaml@main
    with:
      check-name: Test Results
      artifact-pattern: maven-target
      test-result-files: |
        target/surefire-reports/TEST-*.xml
        target/failsafe-reports/TEST-*.xml
    secrets: inherit
    